// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "github.com/Sion-L/gateway/internal/handler/auth"
	"github.com/Sion-L/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/auth/v1/user"),
	)
}
