// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "github.com/Sion-L/gateway/internal/handler/user"
	"github.com/Sion-L/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ldap/addSource",
				Handler: user.LdapSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ldap/verify",
				Handler: user.LdapVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user/v1"),
	)
}
