// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"github.com/Sion-L/devops/user/internal/logic"
	"github.com/Sion-L/devops/user/internal/svc"
	"github.com/Sion-L/devops/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) LdapSource(ctx context.Context, in *user.LdapSourceReq) (*user.LdapSourceResp, error) {
	l := logic.NewLdapSourceLogic(ctx, s.svcCtx)
	return l.LdapSource(in)
}

func (s *UserServer) LdapVerify(ctx context.Context, in *user.LdapVerifyReq) (*user.LdapVerifyResp, error) {
	l := logic.NewLdapVerifyLogic(ctx, s.svcCtx)
	return l.LdapVerify(in)
}
