// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code    int         `json:"code"`    // 状态码
	Message string      `json:"message"` // 消息
	Data    interface{} `json:"data"`    // 数据
}

type LdapSourceReq struct {
	Host     string `form:"host"`
	Port     int64  `form:"port"`
	Dn       string `form:"dn"`
	Password string `form:"password"`
	Ou       string `form:"ou"`
	Filter   string `form:"filter"`
	UserAttr string `form:"userAttr"`
}

type LdapVerifyReq struct {
	Host     string `form:"host"`
	Port     int64  `form:"port"`
	Dn       string `form:"dn"`
	Password string `form:"password"`
	Ou       string `form:"ou"`
	Filter   string `form:"filter"`
	UserAttr string `form:"userAttr"`
}

type LdapVerifyResp struct {
	Connectivity bool `json:"connectivity"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	UserId   uint64 `json:"userId"`
	Username string `json:"username"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}
