// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type ResponseWithData struct {
	Code    int         `json:"code"`    // 状态码
	Message string      `json:"message"` // 消息
	Data    interface{} `json:"data"`    // 数据
}

type AddMemberOfGroupReq struct {
	Group string `json:"group"`
}

type AddUserReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
	NickName string `form:"nick_name"`
	Email    string `form:"email"`
	Mobile   string `form:"mobile"`
	Source   string `form:"source"`
}

type AddUserToMemberOfGroupReq struct {
	Usernmae string `json:"usernmae"`
	Group    string `json:"group"`
}

type DelMemberOfGroupReq struct {
	Group string `json:"group"`
}

type DeleteUserResp struct {
	UserId int64 `json:"userId"`
}

type GetMemberOfGroupsReq struct {
}

type GetUsersInMemberOfGroupReq struct {
	Group string `json:"group"`
}

type JwtToken struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LdapSourceReq struct {
	Host     string `form:"host"`
	Port     int64  `form:"port"`
	Dn       string `form:"dn"`
	Password string `form:"password"`
	Ou       string `form:"ou"`
	Filter   string `form:"filter"`
	UserAttr string `form:"userAttr"`
}

type LdapVerifyReq struct {
	Host     string `form:"host"`
	Port     int64  `form:"port"`
	Dn       string `form:"dn"`
	Password string `form:"password"`
	Ou       string `form:"ou"`
	Filter   string `form:"filter"`
	UserAttr string `form:"userAttr"`
}

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResp struct {
	Username string `json:"username"`
	JwtToken struct {
		AccessToken  string `json:"accessToken"`
		AccessExpire int64  `json:"accessExpire"`
		RefreshAfter int64  `json:"refreshAfter"`
	} `json:"jwtToken"`
}

type RemoveUserToMemberOfGroupReq struct {
	Usernmae string `json:"usernmae"`
	Group    string `json:"group"`
}
