// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

type LoginResp struct {
	UserId   int64  `json:"userId"`
	Username string `json:"username"`
	Token    string `json:"token"`
	ExpireAt int64  `json:"expireAt"`
}
