package user

const (
	LDAP_URL      = "AUTH_LDAP_SERVER_URI"
	LDAP_PASSWORD = "AUTH_LDAP_BIND_PASSWORD"
	LDAP_BINDDN   = "AUTH_LDAP_BIND_DN"
	LDAP_FILTER   = "AUTH_LDAP_SEARCH_FILTER"
	LDAP_OU       = "AUTH_LDAP_SEARCH_OU"
	LDAP_USERATTR = "AUTH_LDAP_USER_ATTR"
)
